version: '3'
services:
  cdktf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event-sys-cdktf
    working_dir: /app
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - .:/app
      - $HOME/.aws/credentials:/home/app/.aws/credentials:ro