version: '3'

tasks:
  cdktf-get:
    desc: Run 'cdktf get' in the Docker container
    cmds:
      - docker exec event-sys-cdktf cdktf get

  npm-install:
    desc: Run 'npm install' in the Docker container
    cmds:
      - docker exec event-sys-cdktf npm install

  cdktf-list:
    desc: Run 'cdktf list' in the Docker container
    cmds:
      - docker exec event-sys-cdktf cdktf list

  deploy-network:
    desc: Deploy the network stack
    cmds:
      - docker exec -it event-sys-cdktf cdktf deploy dev-network-stacks-ap

  deploy-db:
    desc: Deploy the database stack
    cmds:
      - docker exec -it event-sys-cdktf cdktf deploy dev-data-db-stacks-ap

  deploy-eks:
    desc: Deploy the EKS stack
    cmds:
      - docker exec -it event-sys-cdktf cdktf deploy dev-eks-stacks-ap dev-k8s-ap

  deploy-sqs:
    desc: Deploy the SQS stack
    cmds:
      - docker exec -it event-sys-cdktf cdktf deploy dev-sqs-stacks-ap

  configure-aws-credentials:
    desc: Configure AWS credentials for Kubernetes
    cmds:
      - sh local/aws-scripts/configure_aws_credentials.sh
      - docker-compose down
      - docker-compose up -d

  configure-k8s-credentials:
    desc: Configure AWS credentials for Kubernetes
    cmds:
      - docker exec event-sys-cdktf aws eks update-kubeconfig --region ap-northeast-1 --name dev-eks-cluster

  create-s3-bucket:
    desc: Create an S3 bucket
    cmds:
      - docker exec event-sys-cdktf bash -c "chmod +x local/aws-scripts/create_s3_bucket.sh && local/aws-scripts/create_s3_bucket.sh"

  setup-ingress-controller:
    desc: Setup AWS Load Balancer Controller
    cmds:
      - docker exec -it event-sys-cdktf bash service/setup_ingress_controller.sh

  run-all-stacks:
    desc: Run all CDKTerraform stacks
    cmds:
      - task configure-aws-credentials
      - task cdktf-get
      - task npm-install
      - task create-s3-bucket
      - task cdktf-list
      - task deploy-network
      - task deploy-db
      - task deploy-eks
      - task deploy-sqs
      - task configure-k8s-credentials
      - task setup-ingress-controller

  destroy-eks:
    desc: Create an S3 bucket
    cmds:
      - docker exec -it event-sys-cdktf cdktf destroy dev-eks-stacks-ap dev-k8s-ap
      
  run-all-cleanup:
    desc: Cleanup resources
    cmds:
      - task destroy-eks

  run-sample-app:
    desc: Create sample app deployment , service , ingress
    cmds:
      - docker exec -it event-sys-cdktf kubectl apply -f service/echoserver/echoserver-namespace.yaml
      - docker exec -it event-sys-cdktf kubectl apply -f service/echoserver/echoserver-deployment.yaml
      - docker exec -it event-sys-cdktf kubectl apply -f service/echoserver/echoserver-service.yaml
      - docker exec -it event-sys-cdktf kubectl apply -f service/echoserver/echoserver-ingress.yaml